openapi: 3.0.1
info:
  title: All The Flavors
  description: >-
    This is the second version of the ATF API. Find out more at the [official
    site](https://alltheflavors.com).
  termsOfService: >-
    https://app.termly.io/document/terms-of-use-for-website/ea0409b4-1130-468a-b405-e44331c15846
  contact:
    url: 'https://alltheflavors.com'
  version: 2.0.0
servers:
  - url: 'https://alltheflavors.com/api/v2'
  - url: 'http://alltheflavors.com/api/v2'
tags:
  - name: recipe
    description: A recipe of one or more flavorings
  - name: flavor
    description: A flavoring
  - name: tag
    description: A tag describing another entity
  - name: user
    description: A user
paths:
  /recipes:
    get:
      tags:
        - recipe
      summary: Get a list of recipes
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: List of recipes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeResponse'
  /flavors:
    get:
      tags:
        - flavor
      summary: Get a list of flavors
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: List of flavors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlavorResponse'
  /tags:
    get:
      tags:
        - tag
      summary: Get a list of tags
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
  /users:
    get:
      tags:
        - user
      summary: Get a list of users
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  parameters:
    pageNumber:
      in: query
      name: page[number]
      schema:
        type: integer
      required: false
    pageSize:
      in: query
      name: page[size]
      schema:
        type: integer
      required: false
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Internal identifier
          example: 1001
        name:
          type: string
          description: User-defined name
        description:
          type: string
          description: User-defined description
        image_url:
          type: string
          description: URL to a user-defined image
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
        recipe_type:
          type: integer
          format: int32
          description: Undocumented
        recipe_flavors:
          type: array
          items:
            $ref: '#/components/schemas/Flavor'
      xml:
        name: Recipe
    Flavor:
      type: object
      properties:
        mix_id:
          type: integer
          format: int64
          description: Internal identifier
          example: 2088772058219
        mix_sid:
          type: string
          description: External base36 identifier
          example: qnkgyb1n
        name:
          type: string
        vendor:
          type: object
          properties:
            mix_id:
              type: integer
              format: int64
              description: Internal identifier
              example: 2088772058219
            mix_sid:
              type: string
              description: External base36 identifier
              example: qnkgyb1n
            name:
              type: string
            abbreviation:
              type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted:
          type: boolean
        deleted_at:
          type: string
          format: date-time
        recipe_count:
          type: integer
          format: int32
        average_millipercent:
          type: integer
          description: The average concentration of this flavor across all recipes, in millipercent (i.e. 1000 = 100%)
          format: int32
          minimum: 0
          maximum: 1000
        slug:
          type: string
        confirmed:
          type: boolean
          description: True if the flavor has been confirmed as valid
        rejected:
          type: boolean
          description: True if the flavor has been rejected as invalid
        vendor_url:
          type: string
        base:
          type: string
        density:
          type: number
          format: float
        imageUrl:
          type: string
        description:
          type: string
        description_raw:
          type: string
        short_description:
          type: string
        vendor_percentage:
          type: number
          format: float
          minimum: 0
          maximum: 1
        vendor_description_raw:
          type: string
        vendor_description:
          type: string
        other_names:
          type: string
        discontinued:
          type: boolean
        tags:
          type: object
      xml:
        name: Flavor
    Tag:
      type: object
      properties:
        mix_id:
          type: integer
          format: int64
          description: Internal identifier
          example: 2088772058219
        mix_sid:
          type: string
          description: External base36 identifier
          example: qnkgyb1n
        name:
          type: string
        taggings_count:
          type: integer
          format: int32
      xml:
        name: Tag
    User:
      required:
        - id
        - name
      type: object
      properties:
        mix_id:
          type: integer
          format: int64
          description: Internal identifier
          example: 2088772058219
        mix_sid:
          type: string
          description: External base36 identifier
          example: qnkgyb1n
        username:
          type: string
          example: someone
        recent_recipes:
          type: array
          items:
            $ref: '#/components/schemas/Recipe'
        featured_recipes:
          type: array
          items:
            $ref: '#/components/schemas/Recipe'
        recipes:
          type: object
          description: Recipe counts
          properties:
            total:
              type: integer
              format: int32
            private:
              type: integer
              format: int32
            public:
              type: integer
              format: int32
      xml:
        name: User
    RecipeResponse:
      type: array
      items:
        $ref: '#/components/schemas/Recipe'
    FlavorResponse:
      type: array
      items:
        $ref: '#/components/schemas/Flavor'
    TagResponse:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    UserResponse:
      type: array
      items:
        $ref: '#/components/schemas/User'
